# Generated by Django 4.1.7 on 2023-06-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
