# Generated by Django 4.1.7 on 2023-06-01 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextileOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='media/files', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='TextileOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название швейного заказа')),
                ('description', models.CharField(max_length=1024, verbose_name='Описание заказа')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Обрабатывается'), (2, 'Выполнен')], default=1, verbose_name='Статус заказа')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания швейного заказа')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения швейного заказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Заказ активен')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textilefactory.textileorderfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='textile_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Швейный заказ',
                'verbose_name_plural': 'Швейные заказы',
            },
        ),
    ]
