# Generated by Django 4.1.7 on 2023-06-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textilefactory', '0002_textileorder_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textileorder',
            name='phone_number',
        ),
    ]
