# Generated by Django 4.1.7 on 2023-06-01 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания категории')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Категория активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Выполнен', 'Выполнен'), ('Отклонен', 'Отклонен'), ('В ожидании', 'В ожидании'), ('До ожидании', 'До ожидании')], max_length=125, verbose_name='Статус заказа')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения заказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Заказ активен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Имя работника')),
                ('image', models.ImageField(upload_to='media/images', verbose_name='Фото сотрудника')),
                ('description', models.CharField(max_length=255, verbose_name='Описание сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('cover', models.ImageField(upload_to='media/images', verbose_name='Главное фото продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена продукта')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('sex', models.CharField(choices=[('Мужское', 'Мужское'), ('Женское', 'Женское'), ('Детское', 'Детское'), ('Унисекс', 'Унисекс')], max_length=125, verbose_name='Пол')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания продукта')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения продукта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Заказ активен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='buyershop.category', verbose_name='Категория продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения заказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Заказ активен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='buyershop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='buyershop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Детали заказа',
                'verbose_name_plural': 'Детали заказов',
            },
        ),
        migrations.CreateModel(
            name='DetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media/images', verbose_name='Фотографии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buyershop.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Детальная фотография',
                'verbose_name_plural': 'Детальные фотографии',
            },
        ),
    ]
