# Generated by Django 4.1.7 on 2023-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyershop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Имя работника')),
                ('description', models.TextField(verbose_name='Описание сотрудника')),
            ],
            options={
                'verbose_name': 'Наша услуга',
                'verbose_name_plural': 'Наши услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
