# Generated by Django 4.1.7 on 2023-06-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyershop', '0002_ourservice_alter_worker_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='description',
            field=models.TextField(verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Название услуги'),
        ),
    ]
