# Generated by Django 4.1.7 on 2023-06-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyershop', '0004_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='logo',
            field=models.ImageField(default=1, upload_to='media/images'),
            preserve_default=False,
        ),
    ]
