# Generated by Django 4.1.7 on 2023-06-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyershop', '0005_link_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
