# Generated by Django 4.1.7 on 2023-06-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyershop', '0006_link_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='logo',
        ),
        migrations.AddField(
            model_name='link',
            name='social_media',
            field=models.CharField(choices=[('instagram', 'Инстаграм'), ('telegram', 'Телеграм'), ('whatsapp', 'Ватсап'), ('tiktok', 'Тик-ток')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
